sudo: required
services: 
  - docker

before_install :
  - docker build -t ameybhosle3/server -f Dockerfile.dev .

# script:
#   - docker run -e CI=true ameybhosle3/dock npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "ap-south-1"
  app: "Server"
  env: "Server-env"
  bucket_name: "elasticbeanstalk-ap-south-1:039264153064"
  bucket_path: "server"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET


